### ISSUE TITLE
Generate edge weights for SSSP

### ISSUE THREAD

**Issue by ht-gong** [ubc-systopia/margraphita#141]
SSSP needs some random edge weights to run

**Comment by artorhem** [comment]
This is fixed in  d5ccb9e6c6e52ebce4f3cfeea2519dec524de1e9

**Comment by artorhem** [comment]
The random weights must be inserted with the graph at the time of Bulk insertion. the ```-w``` parameter with preprocess.py propagates this switch through all the relevant code paths.
