### ISSUE TITLE
ekey node_cursor segfaults during internal WT call

### ISSUE THREAD

**Issue by JackLiJXL** [ubc-systopia/margraphita#76]
`__wt_schema_project_slice (session=session@entry=0x7ffff7a30e28, cp=cp@entry=0x5555558790d0, proj_arg=0x55555582e0d0 "0ksn0kn", key_only=key_only@entry=true, vformat=0x555555847ac0 "qq", value=value@entry=0x555555878d00)
    at src/schema/schema_project.c:205
205	{
(gdb)
208	    WT_DECL_PACK(pack);
(gdb)
82	    return (__pack_initn(session, pack, fmt, strlen(fmt)));
(gdb)
__pack_init (fmt=0x555555847ac0 "qq", pack=0x7fffffffdcd0, session=0x7ffff7a30e28) at ./src/include/packing.i:65
65	    if (*fmt == '.')
(gdb)

Thread 1 "test_edgekey" received signal SIGSEGV, Segmentation fault.
__strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
120	../sysdeps/x86_64/multiarch/../strlen.S: No such file or directory.`

**Comment by JackLiJXL** [comment]
BUG LOCATED: something wrong in CommonUtil::__record_to_node_ekey

**Comment by apricot2012** [comment]
Further details about bug: dst_src_idx cursor seems to segfault whenever we try to access ATTR, testing code on branch issue#76
